services:
  vnavibackend:
    build: .
    ports:
      - "5001:5001"
    command: python app.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
